"undefined"==typeof window.SC_TeaserBlock&&(window.SC_IIterator=function(a){this.n=a;this.e=0;this.m=a.length},window.SC_IIterator.prototype={next:function(){var a=this.n[this.e];this.e++;this.e==this.m&&(this.e=0);return a}},window.SC_UA=function(){},window.SC_UA.prototype={f:function(){return navigator.userAgent.toLowerCase()},i:function(){return-1!=this.f().indexOf("chrome")},t:function(){return-1!=this.f().indexOf("msie")&&!this.u()},u:function(){return-1!=this.f().indexOf("opera")},z:function(){return!this.i()&&
!this.t()}},window.SC_TBObj=function(){this.A=new window.SC_UA},window.SC_TBObj.prototype={domain:"http://domain.com",i:function(){return-1!=this.f().indexOf("chrome")},v:function(){var a=this.b.params,b="";if(a){var c=0,d;for(d in a){var e=d,i=a[d];c++;b=1==c?b+("?"+e+"="+i):b+("&"+e+"="+i)}}return b},link:function(a,b,c,d){return this.domain+"/click/"+b+"/"+c+"/"+d+"/"+this.v()},j:function(a){var b=[],a=a?a+"_":"";b.push("font-family:"+this.b.code[a+"font_family"]);b.push("font-size:"+this.b.code[a+
"font_size"]+"px");b.push("color:#"+this.b.code[a+"font_color"]);b.push(this.fontWeight(this.b.code[a+"font_bold"]));b.push(this.l(this.b.code[a+"font_underline"]));return b.join("; ")},fontWeight:function(a){var b="font-weight:normal";1==a&&(b="font-weight:bold");return b},l:function(a){var b="text-decoration:none";1==a&&(b="text-decoration:underline");return b},textAlign:function(){var a="text-align:none";switch(this.b.code.text_h_align){case 1:a="text-align:left";break;case 2:a="text-align:center";
break;case 3:a="text-align:right"}return a},g:function(){var a="vertical-align:none";switch(this.b.code.text_v_align){case 1:a="vertical-align:top";break;case 2:a="vertical-align:middle";break;case 3:a="vertical-align:bottom"}return a},q:function(){var a=this.b.code.image_border_size,b=this.b.code.image_border_color,c=this.b.code.image_margin,d=this.b.code.image_size,e=[];0!==a?e.push("border:"+a+"px solid #"+b):e.push("border:none");0!==c&&e.push("margin:"+c+"px");d&&(e.push("width:"+d+"px"),e.push("min-width:"+
d+"px"),e.push("height:"+d+"px"));return e.join("; ")},w:function(){var a=[],b="",c=this.b.code.border_size;0!==c?this.b.code.border_color&&(b="border:"+c+"px solid #"+this.b.code.border_color):b="border: none";a.push(b);this.b.code.background_color&&a.push("background-color:#"+this.b.code.background_color);return a.join("; ")},k:function(){var a=this.b.code.background_color_hover,b=[];b.push("color:#"+this.b.code.font_color_hover);b.push(this.fontWeight(this.b.code.font_bold_hover));b.push(this.l(this.b.code.font_underline_hover));
b.push("font-family:"+this.b.code.font_family_hover);b.push("font-size:"+this.b.code.font_size_hover+"px");var c="";a&&(c+="#"+this.d+"_Table:hover {background: #"+a+" !important}");c+="#"+this.d+" ."+this.d+"_title {"+this.j()+"}";c+="#"+this.d+" ."+this.d+"_title:hover {"+b.join("; ")+"}";return c+="#"+this.d+" ."+this.d+"_title-hover {"+b.join("; ")+"}"},h:function(a,b){var c="";return c=1==b?this.d+"_"+a+"_link":this.d+"_"+a},c:function(a,b,c){a=document.createElement(a);if(b)for(var d in b)"style"==
d?a.style.cssText=b[d]:a.setAttribute(d,b[d]);c&&(a.innerHTML=c);return a},s:function(a,b){document.getElementById(a+"_link").setAttribute("class",b+"_title-hover")},r:function(a,b){var c=document.getElementById(a+"_link");c&&(c.removeAttribute("class"),c.setAttribute("class",b+"_title"))},B:function(a){return!a.match(/:\/\//)?"http://"+a:a},o:function(a,b,c,d){var c=this.c("a",{href:b.lb_click_url,title:b.lb_title,"class":this.d+"_title",className:this.d+"_title",id:this.h(d,1),target:"_blank",rel:"nofollow"},
b.lb_title),e=this.c("a",{href:b.lb_click_url,target:"_blank",title:b.lb_title,rel:"nofollow"}),d=this.c("img",{src:this.B(b.lb_img_url),alt:b.lb_title,style:this.q(),id:this.h(d),onmouseover:"window.SC_TeaserBlock.imgMouseOver(this.id, '"+this.d+"')",onmouseout:"window.SC_TeaserBlock.imgMouseOut(this.id, '"+this.d+"')"}),i=this.c("tbody"),l=this.c("table",{cellspacing:0,cellpadding:0,border:0,width:"auto"}),h=this.c("tr"),j=this.c("tr"),f=this.c("td",{style:this.textAlign()+"; "+this.g()}),g=this.c("td",
{style:this.textAlign()+"; "+this.g()});switch(a){case 1:this.a(f,c);this.a(h,f);this.a(i,h);this.a(e,d);this.a(g,e);this.a(j,g);this.a(i,j);break;case 2:"string"===typeof this.b.code.more_font_family?(a=this.c("tr"),j=this.c("td",{style:"text-align:right; vertical-align:bottom"}),b=this.c("a",{href:b.lb_click_url,target:"_blank",title:"\u0447\u0438\u0442\u0430\u0442\u044c \u0434\u0430\u043b\u0435\u0435",style:this.j("more")+"; margin:10px"},"\u0447\u0438\u0442\u0430\u0442\u044c \u0434\u0430\u043b\u0435\u0435 &raquo;"),
g.setAttribute("rowspan",2),g.setAttribute("width",this.b.code.image_size),l.setAttribute("width","100%"),this.a(j,b),this.a(a,j),this.a(e,d),this.a(g,e),this.a(h,g),this.a(f,c),this.a(h,f),this.a(i,h),this.a(i,a)):(this.a(e,d),this.a(g,e),this.a(h,g),this.a(f,c),this.a(h,f),this.a(i,h));break;case 3:this.a(e,d);this.a(g,e);this.a(j,g);this.a(i,j);this.a(f,c);this.a(h,f);this.a(i,h);break;case 4:this.a(f,c),this.a(h,f),this.a(e,d),this.a(g,e),this.a(h,g),this.a(i,h)}this.a(l,i);return l},a:function(a,
b){a.appendChild(b)},p:function(){function a(a){td.onmouseup=function(){window.open(a)}}var b=this.c("div",{style:"display:none; position:absolute;"}),c="",d=this.b.code_id,e=this.b.code.v_count,i=this.b.code.h_count,l=this.b.code.text_layout,h=0,j=document.getElementById(this.d);if(null===j)throw"block container '"+this.d+"' not found";j.innerHTML="";var f=this.c("style",{type:"text/css"});if(f.styleSheet)f.styleSheet.cssText=this.k();else{var g=document.createTextNode(this.k());this.a(f,g)}this.a(document.getElementsByTagName("head")[0],
f);for(var f=this.c("tbody"),g=this.c("table",{cellspacing:0,cellpadding:0,border:0,width:"auto",style:this.w(),id:this.d+"_Table"}),q=new window.SC_IIterator(this.b.teasers),k=null,m,n=0;n<e;n++){m=this.c("tr");this.a(f,m);for(var o=0;o<i;o++){td=this.c("td",{style:this.textAlign()+"; "+this.g()+"; padding:5px","class":this.d+"_td"});k=q.next();this.A.z()&&k.lb_click_url2&&a(k.lb_click_url2);this.a(m,td);var r=this.o(l,k,d,h);this.a(td,r);k.ad_html&&(c+=k.ad_html);h++}}this.b.ad_html&&(c+=this.b.ad_html);
this.a(f,m);this.a(g,f);this.a(j,g);""!==c&&(b.innerHTML=c,this.a(j,b))},C:function(a,b){this.d=a;this.b=b;this.p()}},window.SC_TeaserBlock=new window.SC_TBObj,window.SC_TeaserBlock.writeBlock=window.SC_TeaserBlock.C,window.SC_TeaserBlock.imgMouseOver=window.SC_TeaserBlock.s,window.SC_TeaserBlock.imgMouseOut=window.SC_TeaserBlock.r);for(var p;p=window.SC_BuildTeaserBlock.pop();)p();
