(function(){function e(){function e(c){if("undefined"==typeof c)return!1;var h=""+c.split("_")[1],d=document.createElement("script");d.type="text/javascript";d.src="http://"+j+"/"+encodeURIComponent(h)+"/"+(new Date).getTime()+".js?r="+g;d.charset="UTF-8"";d.onerror=d.onload=d.onreadystatechange=function(){if(!d.readyState||d.readyState&&("complete"==d.readyState||"loaded"==d.readyState)){d.onerror=d.onload=d.onreadystatechange=null;d.parentNode.removeChild(this);delete d;m.run();var a=!1,f="",g="",
e=!1,v=!1,j={};try{document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title")&&(a=!0,f=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title-prepend"),g=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title-append")),document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-increase-when-hover")&&(e=!0),document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-shake-first")&&
(v=!0,j=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-shake-first"),j=eval("("+j+")"))}catch(n){}if(10<b.length&&1<b.split(" ").length&&a)try{var r=document.getElementById(c).getElementsByClassName("teaser-cc-title")[0].getElementsByTagName("a")[0],p=b;if(!f)try{p=p.substr(0,1).toUpperCase()+p.substr(1)}catch(q){}"undefined"!=typeof r.innerText?r.innerText=f+p+g:r.textContent=f+p+g}catch(u){}if(e)try{for(var r=y(document.getElementById(c),"teaser-cc-img"),x=document.getElementById(c).getElementsByTagName("div")[0],
a=0,z=r.length;a<z;a++){var s=r[a].getElementsByTagName("img")[0];try{s.setAttribute("data-increase-when-hover","200px"),s.setAttribute("id",h+"_"+a),s.onmouseover=function(){(new A).start(this.id,this.width,200,"",x.id+"_expanded")}}catch(C){}}}catch(D){}if(v)try{var p=document.getElementById(c).getElementsByTagName("td")[0],s=p.getElementsByTagName("table")[0],t=document.createElement("div");t.className="bl-shake-teaser";t.appendChild(s);p.appendChild(t);var w=new B;w.init(t,j);window.setTimeout(function(){w.scroll()},
2E3,w)}catch(E){}}};document.getElementsByTagName("body")[0].appendChild(d)}var j="t.teaser.cc",m=this;this.unique={};this.queue=[];this.push=function(c){if(this.unique[c])return!1;this.unique[c]=c;this.queue.push(c)};this.pop=function(){return this.queue.shift()};this.run=function(){e(this.pop())};var g;a:{var f=[[/^http:\/\/(?:\w+\.)?yandex\.[a-z]+/,/text=([^&]+)/],[/^http:\/\/(?:\w+\.)?mail\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?rambler\.[a-z]+/,/query=([^&]+)/],[/^http:\/\/(?:\w+\.)?ask\.[a-z]+/,
/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?webalta\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?bing\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?qip\.[a-z]+/,/query=([^&]+)/]],a,h;for(h in f)if(a=f[h],document.referrer.match(a[0])&&document.referrer.match(a[1])){f=document.referrer.match(a[1]);g=f.length?f[1]:"";break a}g=""}var b=decodeURIComponent(g).replace(/\+/g," ");this.render=function(c){var b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText=c.style:b.appendChild(document.createTextNode(c.style));
document.getElementsByTagName("head")[0].appendChild(b);document.getElementsByTagName("head");var d=document.getElementById("TCCB_"+c.oid);if("undefined"==typeof d)return!1;d.innerHTML=c.data;setTimeout(function(){for(var b=d.getElementsByTagName("table"),a=0,h=b.length;a<h;a++)for(var f=b[a].getElementsByTagName("a"),g=0,k=f.length;g<k;g++)try{var e=c.urls[a]+(1<c.urls[a].split("?").length?"&":"?"),j="";"undefined"!=typeof document.referrer&&document.referrer&&(j="&",e=e+"f="+encodeURIComponent(document.referrer));
"undefined"!=typeof screen&&screen&&(e=e+j+"s="+encodeURIComponent(screen.width+"x"+screen.height+"x"+screen.colorDepth));f[g].href=e}catch(v){}},700,d,c)}}function A(){function e(f,a,h){var b=g.createElement(f);if("undefined"!==typeof a)for(f in a){var c=b,k=f,d=a[f];if("class"==k)c.className=d;else if("object"==typeof d){var i=void 0;for(i in d)c[k][i]=d[i]}else"onmouseover"==k||"onmouseout"==k?c.b=d:c[k]=d}"undefined"!==typeof h&&(b.innerHTML=h);return b}function j(f,a,h,b,c,e,d){var i=g.getElementById(f),
l=i.getElementsByTagName("img")[0],a=parseInt(a),h=parseInt(h),c=parseInt(c),b=parseInt(b);a<h?(c-=1,b-=1,a+=2,i.style.width=i.style.height=l.style.width=l.style.height=a+"px",i.style.top=c+"px",i.style.left=b+"px",setTimeout(function(){j(f,a,h,b,c,e,d)},10)):(re=RegExp("_"+e+"_"),l.src=g.getElementById(d).src.replace(re,"_"+h+"_"));l.onmouseout=function(){m(f,a,e,b,c)}}function m(f,a,h,b,c){var e=g.getElementById(f),d=e.getElementsByTagName("img")[0];d.onmouseover=null;a=parseInt(a);h=parseInt(h);
c=parseInt(c);b=parseInt(b);a>h?(a-=2,c+=1,b+=1,e.style.top=c+"px",e.style.left=b+"px",d.style.width=d.style.height=e.style.width=e.style.height=a+"px",setTimeout(function(){m(f,a,h,b,c)},10)):e.style.display="none"}var g=window.document;this.start=function(f,a,h,b,c){var k=g.getElementById(f),d;d=k;if(d.getBoundingClientRect){d=d.getBoundingClientRect();var i=document.body;d={top:Math.round(d.top+(window.pageYOffset||g.scrollTop||i.scrollTop)-(g.clientTop||i.clientTop||0)),left:Math.round(d.left+
(window.pageXOffset||g.scrollLeft||i.scrollLeft)-(g.clientLeft||i.clientLeft||0))}}else{for(var l=i=0;d;)i+=parseFloat(d.offsetTop),l+=parseFloat(d.offsetLeft),d=d.offsetParent;d={top:Math.round(i),left:Math.round(l)}}i=d.top;d=d.left;new_id=f+"_expanded";l=g.getElementById(c);null==l&&(l=e("div",{id:c}));c=g.getElementById(new_id);null==c&&(c=e("div",{onmouseover:b.onmouseover,onmouseout:b.onmouseout,id:new_id,style:{position:"absolute",zIndex:"1000",top:i+"px",left:d+"px",width:a+"px",height:a+
"px"}}),b=e("img",{id:f+"_"+h,src:k.src,style:{margin:"0px",padding:"0px"}}),k=e("a",{href:k.parentNode.href,"class":"teaser-cc-img",target:"_blank"}),k.appendChild(b),c.appendChild(k),l.appendChild(c),g.getElementsByTagName("body")[0].appendChild(l));c.style.display="block";j(new_id,a,h,d,i,a,f)}}function B(){var e=[],j,m,g,f=function(){},a=!1;this.init=function(a,b){e.push(a);j=parseInt(b&&b.radius?b.radius:10);m=parseInt(b&&b.timeline?b.timeline:1E3);g=parseInt(b&&b.step?b.step:50);f=b&&b.callback?
b.callback:function(){}};this.shake=function(){var a=window.setInterval(function(){var b="left: "+Math.round(2*Math.random()*j-j)+"px; ",b=b+("top: "+Math.round(2*Math.random()*j-j)+"px; ");e[0].style.cssText=b},g);window.setTimeout(function(){window.clearInterval(a);window.setTimeout(function(){e[0].style.cssText="left: 0px; top: 0px;";f()},g)},m);return!0};this.scroll=function(){var e=this;a=window.setInterval(function(){e.isOnScroll(e)&&e._off_scroll()},50,e)};this._off_scroll=function(){window.clearInterval(a)};
this.isOnScroll=function(a){var b=a._get_window_height(),c=a._get_window_Yscroll(),f=a._get_offsetTop(e[0]),d=a._get_element_Height(e[0]);return f+d<=c+b&&a.shake()};this._get_window_height=function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0};this._get_window_Yscroll=function(){return window.pageYOffset||document.body.scrollTop||document.documentElement.scrollTop||0};this._get_element_Height=function(a){return a.offsetHeight||a.scrollTop||0};
this._get_offsetTop=function(a){var b=0;do b+=a.offsetTop;while(a=a.offsetParent);return b}}function y(e,j){for(var m=[],g=RegExp("(^| )"+j+"( |$)"),f=e.getElementsByTagName("*"),a=0,h=f.length;a<h;a++)g.test(f[a].className)&&m.push(f[a]);return m}for(var x=/^TCCB_\d+$/,u=document.getElementsByTagName("div"),q=[],n=-1;q[++n]=u[n];);q.length--;"undefined"==typeof $__tccLdr&&($__tccLdr=new e);n=0;for(u=q.length;n<u;n++)q[n].id&&q[n].id.match(x)&&$__tccLdr.push(q[n].id);$__tccLdr.run()})();
function clmapMessage(e){"http://clmap.teaser.cc"==e.origin&&("clmap_setup"==e.data.func?(e=document.createElement("link"),e.rel="stylesheet",e.type="text/css",e.href="http://clmap.teaser.cc/static/clmap.css",document.getElementsByTagName("head")[0].appendChild(e),e=document.createElement("script"),e.src="http://clmap.teaser.cc/static/clmap.js",document.body.appendChild(e)):"clmap_hg_epath"==e.data.func&&_CLMAP.hg_epath(e.data.epath))}
window.addEventListener?window.addEventListener("message",clmapMessage,!1):window.attachEvent("onmessage",clmapMessage);
